### ISSUE TITLE
组队报名信息填写提醒

### ISSUE THREAD

**Issue by Bot4Hackathon2020** [Midnight-Diner/subnet-detect#1]
你们的队伍还没有填写组队报名信息表，请及时填写如下链接中的问卷，否则我们将无法对你们的项目进行实时监控，最后可能会影响你们的成绩，填写链接：[https://forms.office.com/Pages/ResponsePage.aspx?id=DQSIkWdsW0yxEjajBLZtrQAAAAAAAAAAAAMAADVOd2xURFlFNkxIWktDNzkyU0dDVjdLVU9YWkU3OS4u](link)

**Comment by lrjia** [comment]
done
